/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example;

import java.awt.Color;
import net.schmizz.sshj.SSHClient;
import net.schmizz.sshj.common.IOUtils;
import net.schmizz.sshj.connection.channel.direct.Session;

/**
 * @author user
 */
public class GUI extends javax.swing.JFrame {

  private static final java.util.logging.Logger logger =
      java.util.logging.Logger.getLogger(GUI.class.getName());

  /** Creates new form GUI */
  public GUI() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    ipText = new javax.swing.JTextField();
    usernameText = new javax.swing.JTextField();
    passwordText = new javax.swing.JTextField();
    textMessage = new javax.swing.JTextArea();
    jScrollPane1 = new javax.swing.JScrollPane();

    connectButton = new javax.swing.JButton();
    disconnectButton = new javax.swing.JButton();
    sendButton = new javax.swing.JButton();
    advSettingsButton = new javax.swing.JButton();

    connectionLabel = new javax.swing.JLabel();

    zipCheck = new javax.swing.JCheckBox();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    ipText.setForeground(new Color(153, 153, 153));
    ipText.setText("Receiver IP");
    ipText.setToolTipText("Receiver IP");
    ipText.addFocusListener(
        new java.awt.event.FocusAdapter() {
          public void focusGained(java.awt.event.FocusEvent evt) {
            ipTextFocusGained(evt);
          }

          public void focusLost(java.awt.event.FocusEvent evt) {
            ipTextFocusLost(evt);
          }
        });
    ipText.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            ipTextActionPerformed(evt);
          }
        });

    usernameText.setForeground(new Color(153, 153, 153));
    usernameText.setText("username");
    usernameText.addFocusListener(
        new java.awt.event.FocusAdapter() {
          public void focusGained(java.awt.event.FocusEvent evt) {
            usernameTextFocusGained(evt);
          }

          public void focusLost(java.awt.event.FocusEvent evt) {
            usernameTextFocusLost(evt);
          }
        });
    usernameText.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            usernameTextActionPerformed(evt);
          }
        });

    passwordText.setForeground(new Color(153, 153, 153));
    passwordText.setText("password");
    passwordText.addFocusListener(
        new java.awt.event.FocusAdapter() {
          public void focusGained(java.awt.event.FocusEvent evt) {
            passwordTextFocusGained(evt);
          }

          public void focusLost(java.awt.event.FocusEvent evt) {
            passwordTextFocusLost(evt);
          }
        });
    passwordText.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            passwordTextActionPerformed(evt);
          }
        });

    textMessage.setColumns(40);
    textMessage.setLineWrap(true);
    textMessage.setRows(5);
    textMessage.setForeground(new Color(153, 153, 153));
    textMessage.setText("Hello world");
    jScrollPane1.setViewportView(textMessage);

    textMessage.addFocusListener(
        new java.awt.event.FocusAdapter() {
          public void focusGained(java.awt.event.FocusEvent evt) {
            textMessageFocusGained(evt);
          }

          public void focusLost(java.awt.event.FocusEvent evt) {
            textMessageFocusLost(evt);
          }
        });

    connectButton.setText("Connect");
    connectButton.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            connectButtonActionPerformed(evt);
          }
        });

    disconnectButton.setText("Disconnect");
    disconnectButton.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            disconnectButtonActionPerformed(evt);
          }
        });

    sendButton.setText("Send");
    sendButton.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            sendButtonActionPerformed(evt);
          }
        });

    advSettingsButton.setText("Advanced Settings");
    advSettingsButton.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            advSettingsButtonActionPerformed(evt);
          }
        });

    connectionLabel.setText("Not Connected...");

    zipCheck.setText(".zip");
    zipCheck.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            zipCheckActionPerformed(evt);
          }
        });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(zipCheck)
                                    .addContainerGap(
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(
                                                layout
                                                    .createSequentialGroup()
                                                    .addComponent(
                                                        ipText,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        95,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement
                                                            .RELATED)
                                                    .addComponent(
                                                        usernameText,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        71,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement
                                                            .RELATED)
                                                    .addComponent(
                                                        passwordText,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        71,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement
                                                            .RELATED)
                                                    .addComponent(connectButton)
                                                    .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement
                                                            .RELATED)
                                                    .addComponent(disconnectButton)
                                                    .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(
                                                layout
                                                    .createSequentialGroup()
                                                    .addComponent(
                                                        jScrollPane1,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(
                                                layout
                                                    .createSequentialGroup()
                                                    .addGap(0, 0, Short.MAX_VALUE)
                                                    .addComponent(sendButton))
                                            .addGroup(
                                                layout
                                                    .createSequentialGroup()
                                                    .addComponent(connectionLabel)
                                                    .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement
                                                            .RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE)
                                                    .addComponent(advSettingsButton)))
                                    .addContainerGap()))));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                ipText,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                usernameText,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(connectButton)
                            .addComponent(
                                passwordText,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(disconnectButton))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                connectionLabel,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                16,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(advSettingsButton))
                    .addGap(3, 3, 3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(
                        jScrollPane1,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(zipCheck)
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                    .addComponent(sendButton)
                    .addContainerGap()));

    pack();
  } // </editor-fold>

  private static SSHClient client;

  private void textMessageFocusGained(
      java.awt.event.FocusEvent evt) { // GEN-FIRST:event_jTextField2FocusGained
    // TODO add your handling code here:
    if (textMessage.getText().equals("Hello world")) {
      textMessage.setText("");
      textMessage.setForeground(new Color(0, 0, 0));
    }
  } // GEN-LAST:event_jTextField2FocusGained

  private void textMessageFocusLost(
      java.awt.event.FocusEvent evt) { // GEN-FIRST:event_jTextField2FocusLost
    // TODO add your handling code here:
    if (textMessage.getText().equals("")) {
      textMessage.setText("Hello world");
      textMessage.setForeground(new Color(153, 153, 153));
    }
  } // GEN-LAST:event_jTextField2FocusLost

  private void zipCheckActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jCheckBox1ActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_jCheckBox1ActionPerformed

  private void ipTextActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jTextField2ActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_jTextField2ActionPerformed

  private void connectButtonActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jButton1ActionPerformed
    boolean isMissing =
        ipText.getForeground().equals(new Color(153, 153, 153))
            || ipText.getText().trim().isEmpty()
            || usernameText.getForeground().equals(new Color(153, 153, 153))
            || usernameText.getText().trim().isEmpty()
            || passwordText.getForeground().equals(new Color(153, 153, 153))
            || passwordText.getText().trim().isEmpty();

    String hostIP = ipText.getText().trim();
    String username = usernameText.getText().trim();
    String password = passwordText.getText().trim();
    String hostname = "None";

    if (isMissing) {
      connectionLabel.setForeground(Color.GRAY);
      connectionLabel.setText("Missing Field");
    } else {
      try {
        client = Main.connect(hostIP, username, password);
        Session session = client.startSession();
        Session.Command cmd = session.exec("hostname");
        hostname = IOUtils.readFully(cmd.getInputStream()).toString();
        session.close();
        connectionLabel.setForeground(Color.GREEN);
        connectionLabel.setText("Connected! At " + username + "@" + hostname);
      } catch (Exception e) {
        connectionLabel.setForeground(Color.RED);
        connectionLabel.setText("Error Connecting...");
      }
    }
  } // GEN-LAST:event_jButton1ActionPerformed

  private void usernameTextActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jTextField3ActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_jTextField3ActionPerformed

  private void ipTextFocusGained(
      java.awt.event.FocusEvent evt) { // GEN-FIRST:event_jTextField2FocusGained
    // TODO add your handling code here:
    if (ipText.getText().equals("Receiver IP")) {
      ipText.setText("");
      ipText.setForeground(new Color(0, 0, 0));
    }
  } // GEN-LAST:event_jTextField2FocusGained

  private void ipTextFocusLost(
      java.awt.event.FocusEvent evt) { // GEN-FIRST:event_jTextField2FocusLost
    // TODO add your handling code here:
    if (ipText.getText().equals("")) {
      ipText.setText("Receiver IP");
      ipText.setForeground(new Color(153, 153, 153));
    }
  } // GEN-LAST:event_jTextField2FocusLost

  private void usernameTextFocusGained(
      java.awt.event.FocusEvent evt) { // GEN-FIRST:event_jTextField3FocusGained
    // TODO add your handling code here:
    if (usernameText.getText().equals("username")) {
      usernameText.setText("");
      usernameText.setForeground(new Color(0, 0, 0));
    }
  } // GEN-LAST:event_jTextField3FocusGained

  private void usernameTextFocusLost(
      java.awt.event.FocusEvent evt) { // GEN-FIRST:event_jTextField3FocusLost
    // TODO add your handling code here:
    if (usernameText.getText().equals("")) {
      usernameText.setText("username");
      usernameText.setForeground(new Color(153, 153, 153));
    }
  } // GEN-LAST:event_jTextField3FocusLost

  private void sendButtonActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_jButton2ActionPerformed

  private void advSettingsButtonActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jButton3ActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_jButton3ActionPerformed

  private void passwordTextFocusGained(
      java.awt.event.FocusEvent evt) { // GEN-FIRST:event_jTextField4FocusGained
    // TODO add your handling code here:
    if (passwordText.getText().equals("password")) {
      passwordText.setText("");
      passwordText.setForeground(new Color(0, 0, 0));
    }
  } // GEN-LAST:event_jTextField4FocusGained

  private void passwordTextFocusLost(
      java.awt.event.FocusEvent evt) { // GEN-FIRST:event_jTextField4FocusLost
    // TODO add your handling code here:
    if (passwordText.getText().equals("")) {
      passwordText.setText("password");
      passwordText.setForeground(new Color(153, 153, 153));
    }
  } // GEN-LAST:event_jTextField4FocusLost

  private void passwordTextActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jTextField4ActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_jTextField4ActionPerformed

  private void disconnectButtonActionPerformed(java.awt.event.ActionEvent evt) {
    Main.disconnect(client);
    connectionLabel.setText("Not Connected...");
    connectionLabel.setForeground(new Color(153, 153, 153));
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info :
          javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new GUI().setVisible(true));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton connectButton;
  private javax.swing.JButton sendButton;
  private javax.swing.JButton advSettingsButton;
  private javax.swing.JButton disconnectButton;
  private javax.swing.JCheckBox zipCheck;
  private javax.swing.JLabel connectionLabel;
  private javax.swing.JTextArea textMessage;
  private javax.swing.JTextField ipText;
  private javax.swing.JTextField usernameText;
  private javax.swing.JTextField passwordText;
  private javax.swing.JScrollPane jScrollPane1;
  // End of variables declaration//GEN-END:variables
}
